apiVersion: soh.re/v1alpha1
kind: DedicatedService
metadata:
  name: soh.re
spec:
  image: zot.soh.re/soh.re:latest
  port: 8080
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  service:
    type: ClusterIP
    port: 9090
