package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DedicatedServiceSpec defines the desired state of DedicatedService
type DedicatedServiceSpec struct {
	// Image is the container image to use for the pods
	// +kubebuilder:validation:Required
	Image string `json:"image"`

	// Port is the port the container listens on
	// +kubebuilder:default=8080
	// +optional
	Port int32 `json:"port,omitempty"`

	// Replicas is the number of pods to maintain
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=0
	// +optional
	Replicas int32 `json:"replicas,omitempty"`

	// Resources are the resource requirements for the pods
	// +optional
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// Env is a list of environment variables
	// +optional
	Env []corev1.EnvVar `json:"env,omitempty"`

	// Service defines the proxy service configuration
	// +optional
	Service *ServiceConfig `json:"service,omitempty"`
}

// ServiceConfig defines the proxy service configuration
type ServiceConfig struct {
	// Type is the service type (ClusterIP, LoadBalancer, NodePort)
	// +kubebuilder:default=ClusterIP
	// +kubebuilder:validation:Enum=ClusterIP;LoadBalancer;NodePort
	// +optional
	Type corev1.ServiceType `json:"type,omitempty"`

	// Port is the port the proxy service listens on
	// +kubebuilder:default=9090
	// +optional
	Port int32 `json:"port,omitempty"`

	// Annotations for the service
	// +optional
	Annotations map[string]string `json:"annotations,omitempty"`
}

// DedicatedServiceStatus defines the observed state of DedicatedService
type DedicatedServiceStatus struct {
	// AvailableReplicas is the number of ready pods
	// +optional
	AvailableReplicas int32 `json:"availableReplicas,omitempty"`

	// TotalTargets is the total number of target pods
	// +optional
	TotalTargets int32 `json:"totalTargets,omitempty"`

	// AvailableTargets is the number of target pods ready and not in use
	// +optional
	AvailableTargets int32 `json:"availableTargets,omitempty"`

	// Conditions represent the latest available observations
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:shortName=dedi
// +kubebuilder:printcolumn:name="Image",type=string,JSONPath=`.spec.image`
// +kubebuilder:printcolumn:name="Total",type=integer,JSONPath=`.status.totalTargets`
// +kubebuilder:printcolumn:name="Available",type=integer,JSONPath=`.status.availableTargets`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// DedicatedService is the Schema for the dedicatedservices API
type DedicatedService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DedicatedServiceSpec   `json:"spec,omitempty"`
	Status DedicatedServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DedicatedServiceList contains a list of DedicatedService
type DedicatedServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DedicatedService `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DedicatedService{}, &DedicatedServiceList{})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedServiceSpec) DeepCopyInto(out *DedicatedServiceSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedServiceSpec.
func (in *DedicatedServiceSpec) DeepCopy() *DedicatedServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DedicatedServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedServiceStatus) DeepCopyInto(out *DedicatedServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedServiceStatus.
func (in *DedicatedServiceStatus) DeepCopy() *DedicatedServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DedicatedServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedService) DeepCopyInto(out *DedicatedService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedService.
func (in *DedicatedService) DeepCopy() *DedicatedService {
	if in == nil {
		return nil
	}
	out := new(DedicatedService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedServiceList) DeepCopyInto(out *DedicatedServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DedicatedService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedServiceList.
func (in *DedicatedServiceList) DeepCopy() *DedicatedServiceList {
	if in == nil {
		return nil
	}
	out := new(DedicatedServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
